### ISSUE TITLE
logger.xxx 相关方法与 com.jrasp.api.log.Log 接口参数不匹配

### ISSUE THREAD

**Issue by M1nSec** [jvm-rasp/jrasp-modules#1]
https://github.com/jvm-rasp/jrasp-modules/ 这个项目 jrasp-modules 下许多检测插件 logger.xxx 相关方法与 com.jrasp.api.log.Log 接口参数不匹配
![image](https://user-images.githubusercontent.com/44919834/160273367-c19fa32f-1194-49a4-a207-648e69668ca8.png)

且 jrasp-modules 项目 POM 文件 parent 元素下 groupId 为 com.jrasp 的 version 为 1.0。而 https://github.com/jvm-rasp/jrasp-agent 的 version 为 1.0.2。

想了解一下 jrasp-moudles 最新版本是否已经解决

**Comment by xl1605368195** [comment]
agent/module 版本没有同步。最新版本代码已经同步
